const mongoose = require("mongoose");
const blogSchema = new mongoose.Schema({
  title: String,
  image: String,
  publishedDate: String,
  description: String,
  symbol: String,
  design: String,
  design2: String,
  designImg: String,
  // designImage: String,
  pse: String,
  inspiration: String,
  inspirationImg: String,
  designProcess: String,
  designProcessImg: String,
  significance: String,
  material: String,
  materialParagraph: String,
  fashion: String,
  printing: String,
  img: String,
  feedback: String,
  lesson: String,
  credit: String,
  logo: String,
  author: String,
  theDesign: String,
  palms: String,
  theInspiration: String,
  materials: String,
  print: String,
  sigMean: String,
  MatColor: String,
  drawnLesson: String,
  Feedback: String,
  Credit: String,
  Composition: String,
  Logo: String,
  logoImg: String,
  DesignProcess: String,
});

const Blog = mongoose.model("blogs", blogSchema);

module.exports = Blog;
